# Generated by Django 3.1.1 on 2020-09-13 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Equipemt ID')),
                ('equipment_name', models.CharField(max_length=100, verbose_name='Equipment Name')),
                ('primary_desc', models.CharField(max_length=1000, verbose_name='Primary Description')),
                ('rental', models.DecimalField(decimal_places=3, help_text='₹/Hour', max_digits=5, verbose_name='Rate per hour')),
                ('secondary_desc', models.TextField(verbose_name='Secondary Description')),
                ('primary_img', models.ImageField(upload_to='', verbose_name='Primary Image')),
            ],
        ),
        migrations.CreateModel(
            name='Secondary_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(upload_to='', verbose_name='Image ID')),
                ('secondary_img', models.ImageField(upload_to='', verbose_name='Secondary Name')),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.equipment')),
            ],
        ),
    ]
