# Generated by Django 3.1.1 on 2020-09-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondary_image',
            name='id',
        ),
        migrations.AlterField(
            model_name='secondary_image',
            name='image_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Image ID'),
        ),
    ]
