# Generated by Django 3.1.1 on 2020-09-13 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200913_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='secondary_img',
        ),
        migrations.RemoveField(
            model_name='secondary_image',
            name='equipment_id',
        ),
        migrations.AddField(
            model_name='secondary_image',
            name='equipment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.equipment'),
            preserve_default=False,
        ),
    ]
